trigger: none

schedules:
- cron: "0 */3 * * *"
  displayName: 'Compilação a cada 3 horas'
  branches:
    include:
    - main
  always: true

jobs:

- job: 'Test'
  displayName: 'RobotFramework'
  pool:
    vmImage: 'windows-latest'
  strategy:    
    maxParallel: 1

  steps:
    - task: UsePythonVersion@0
      displayName: 'Usa o Python versão 3.x'

    - script: 'pip install robotframework robotframework-seleniumlibrary && npm install chromedriver'
      displayName: 'Instala o Robot + Selenium'

    - script: 'robot --pythonpath . -x outputxunit.xml $(Build.SourcesDirectory)\RobotFramework\Tests'
      displayName: 'Executa os testes'
      continueOnError: true

    - task: PublishTestResults@2
      displayName: 'Publica o resultado dos testes'
      inputs:
        testResultsFiles: outputxunit.xml
        testRunTitle: 'Testes automatizados de UI'